Update supported_schools.txt
soroushamdg/acd pull request #282
Opened 2020-09-13 09:24 UTC by amin3349

2020-09-22 11:44 UTC, maxportit commented
online.done.ir

2020-11-01 18:03 UTC, aghakhaniamir commented
45.129.37.85

2020-11-02 02:07 UTC, amir1914 commented
lms.shahed.ac.ir

2020-11-02 16:38 UTC, masoodderakhshan commented
https://lms12.tabrizu.ac.ir/LoginPage.aspx?F=b

2020-11-04 07:57 UTC, mohammadqwer commented
lms.kashanu.ac.ir

2020-11-04 08:24 UTC, behnam13690 commented
https://lms3.alzahra.ac.ir/my/

2020-11-05 07:32 UTC, keivan-shk commented
lms99.scu.ac.ir
meeting.scu.ac.ir

2020-11-06 02:08 UTC, mohammadqwer commented
https://lms.kashanu.ac.ir

2020-11-07 02:27 UTC, mohammadqwer commented
http://adobe1.kashanu.ac.ir/p54ybor0k7du/?session=breezbreezbktxfu2ghdfzaisc&proto=true
لطفا این دانشگاه را هم اضافه کنید

2020-11-07 02:37 UTC, mohammadqwer commented
لطفا این دانشگاه را هم اضافه کنید
لینک جلسه:
http://adobe1.kashanu.ac.ir/p54ybor0k7du/?session=breezbreezbktxfu2ghdfzaisc&proto=true
لینک lms :
http://lms.kashanu.ac.ir

2020-11-07 13:11 UTC, Alikousali commented
لطفا این دانشگاه را هم اضافه کنید
adobe1.gu.ac.ir
adobe2.gu.ac.ir
adobe3.gu.ac.ir
adobe4.gu.ac.ir

2020-11-07 16:09 UTC, Mohammad610810 commented
https://shahed9.viannacloud.ir/LoginPage.aspx?ReturnUrl=%2f

2020-11-08 09:45 UTC, daazer commented
https://elearn.ut.ac.ir/

2020-11-08 15:09 UTC, hmsh0 commented
https://lms.sirjantech.ac.ir/

2020-11-08 17:49 UTC, yaghoot96 commented
lms1.aui.ac.ir

2020-11-09 06:59 UTC, antijocker commented
لطفا این را هم اضافه کنید:
http://elr.shbu.ac.ir/
جلسه هم:
http://vc.shbu.ac.ir/

2020-11-09 07:01 UTC, antijocker requested changes
http://vc.shbu.ac.ir/
http://elr.shbu.ac.ir/

2020-11-09 07:02 UTC, antijocker requested changes

2020-11-09 07:02 UTC, antijocker commented on supported_schools.txt
> +lms.nlai.ir
http://elr.shbu.ac.ir/
http://vc.shbu.ac.ir/

2020-11-09 08:37 UTC, Almasenahan commented
Hi plase add this school too 

http://vc.farspnu.ac.ir/

http://lms.vc.farspnu.ac.ir/course-196-session-33043?cmd=join-session-record&record=585258&path=%2Fpy7uyc1yhp2k%2F&session=33043

Paym noor shiraz

2020-11-09 15:14 UTC, ahayati1998 commented on supported_schools.txt
> +lms.nlai.ir
```suggestion
vc1.bkatu.ac.ir
```

2020-11-10 08:02 UTC, nikialiiii commented
lms2.sbu.ac.ir 
plz add

2020-11-10 15:29 UTC, hhn55555 commented
Hi dear soroush

please add  https://lms.iranian.ac.ir  

thanks

ضمنا سایت  
https://ffmpeg.zeranoe.com
ظاهراً متوقف شده و من این سورس رو امتحان کردم
https://www.videohelp.com/download/ffmpeg-4.3.1-win64-static.zip

2020-11-11 09:00 UTC, mgolrangi commented
please add http://lms.gut.ac.ir/

2020-11-13 09:31 UTC, mj315 commented
please add 
http://fani.lms991.araku.ac.ir:83
http://adbfani.araku.ac.ir/plmlj37goolv/

2020-11-15 13:23 UTC, shayan1999 commented
سلام مال ما دانشگاه بهشتیه بعد شما لینک زیرو گذاشتد
vu.sbu.ac.ir
ولی اینجا ما لاگین نمیکنیم توی لینک زیر لاگین میکنیم
lms2.sbu.ac.ir
و لینک ویدی‌هامون تو قالب 
vu15.sbu.ac.ir  هستش که عددش عوض میشه
الان نمیدونیم کدومو باید اضافه کنید ولی لطفا مارو هم اضافه کنید :))

2020-11-17 14:37 UTC, amori-naaim commented
آقا لطفا سیستم جهاد دانشگاهی اهوار هم ادد کنید 
lms.jahadp.ir

2020-11-18 20:17 UTC, closed without merging

2020-11-20 21:08 UTC, hmsh0 commented
سلام لطفا دانشگاه صنعتی سیرجان راهم اضافه کنید .
lms.sirjantech.ac.ir

On Wed, Nov 18, 2020, 23:47 Soroush M Pour <notifications@github.com> wrote:

> Closed #282 <https://github.com/soroushamdg/acd/pull/282>.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/soroushamdg/acd/pull/282#event-4012568715>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ARVV3Y4YZM5RQREZ6OGBQJ3SQQTXHANCNFSM4RKRVKZA>
> .
>